# Generated by Django 4.2.1 on 2023-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitFly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avg_count', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
