# Generated by Django 4.2.1 on 2023-11-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insects', '0002_alter_fruitfly_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitfly',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
