# Generated by Django 4.2.1 on 2023-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insects', '0003_alter_fruitfly_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitfly',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fruitfly',
            name='time_stamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
